# Generated by Django 4.1.5 on 2023-03-15 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
