# Generated by Django 4.1.5 on 2023-03-15 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('phone_num', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('cnt', models.CharField(max_length=3, verbose_name='Количество')),
                ('rt', models.DateTimeField(verbose_name='Время')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.product', verbose_name='Продукт')),
            ],
        ),
    ]
